(function() {var implementors = {};
implementors['ruroonga_client'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='ruroonga_client/struct.HTTPRequest.html' title='ruroonga_client::HTTPRequest'>HTTPRequest</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='ruroonga_client/struct.URIBase.html' title='ruroonga_client::URIBase'>URIBase</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='ruroonga_client/builtin/command_query/struct.CommandQuery.html' title='ruroonga_client::builtin::command_query::CommandQuery'>CommandQuery</a>&lt;'a&gt;",];implementors['ruroonga_client'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='ruroonga_client/struct.HTTPRequest.html' title='ruroonga_client::HTTPRequest'>HTTPRequest</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='ruroonga_client/struct.URIBase.html' title='ruroonga_client::URIBase'>URIBase</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='ruroonga_client/builtin/command_query/struct.CommandQuery.html' title='ruroonga_client::builtin::command_query::CommandQuery'>CommandQuery</a>&lt;'a&gt;",];implementors['ruroonga_client'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='ruroonga_client/struct.HTTPRequest.html' title='ruroonga_client::HTTPRequest'>HTTPRequest</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='ruroonga_client/struct.URIBase.html' title='ruroonga_client::URIBase'>URIBase</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='ruroonga_client/builtin/command_query/struct.CommandQuery.html' title='ruroonga_client::builtin::command_query::CommandQuery'>CommandQuery</a>&lt;'a&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
