(function() {var implementors = {};
implementors['ruroonga_client'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='ruroonga_client/struct.Rows.html' title='ruroonga_client::Rows'>Rows</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='ruroonga_client/struct.ResultParser.html' title='ruroonga_client::ResultParser'>ResultParser</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='ruroonga_client/struct.RequestURI.html' title='ruroonga_client::RequestURI'>RequestURI</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='ruroonga_client/struct.URIBase.html' title='ruroonga_client::URIBase'>URIBase</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='ruroonga_client/builtin/command_query/struct.CommandQuery.html' title='ruroonga_client::builtin::command_query::CommandQuery'>CommandQuery</a>&lt;'a&gt;",];implementors["ruroonga_client"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='ruroonga_client/struct.Rows.html' title='ruroonga_client::Rows'>Rows</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='ruroonga_client/struct.ResultParser.html' title='ruroonga_client::ResultParser'>ResultParser</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='ruroonga_client/struct.RequestURI.html' title='ruroonga_client::RequestURI'>RequestURI</a>&lt;'a&gt;","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='ruroonga_client/struct.URIBase.html' title='ruroonga_client::URIBase'>URIBase</a>&lt;'a&gt;","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='ruroonga_client/builtin/command_query/struct.CommandQuery.html' title='ruroonga_client::builtin::command_query::CommandQuery'>CommandQuery</a>&lt;'a&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
